### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by albertonavarro087** [foxnewsnetwork/ember-timezone-input#3]

**Comment by foxnewsnetwork** [comment]
Not recently; I don't think there's anything broken / deprecated about it, though

**Comment by albertonavarro087** [comment]
actually https://github.com/foxnewsnetwork/ember-timezone-input/issues/1 still happening, It produce an error during ember install command

**Comment by foxnewsnetwork** [comment]
Thx for pointing that out, it totally fell off my radar. Will get to it after work

**Comment by albertonavarro087** [comment]
thanks, let me know if you need help

**Comment by foxnewsnetwork** [comment]
fixed the issues, thanks d00d
